//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 安全预警用户端.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysInfoEntities : DbContext
    {
        public SysInfoEntities()
            : base("name=SysInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<adress> adress { get; set; }
        public virtual DbSet<New_Soy> New_Soy { get; set; }
        public virtual DbSet<Pic> Pic { get; set; }
        public virtual DbSet<SensorInfo> SensorInfo { get; set; }
        public virtual DbSet<SoY> SoY { get; set; }
        public virtual DbSet<Sys> Sys { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Syssz> Syssz { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
