//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 安全预警用户端.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Soy
    {
        public int new_SoyID { get; set; }
        public int new_SenID { get; set; }
        public string new_SenIP { get; set; }
        public string new_SenZt { get; set; }
        public Nullable<System.DateTime> new_SoYTime { get; set; }
        public Nullable<int> new_UserID { get; set; }
        public string new_Z { get; set; }
        public string new_D { get; set; }
    
        public virtual SensorInfo SensorInfo { get; set; }
        public virtual User User { get; set; }
    }
}
