//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 安全预警用户端.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoY
    {
        public int SoyID { get; set; }
        public Nullable<int> SenID { get; set; }
        public string SenIP { get; set; }
        public string SenZt { get; set; }
        public Nullable<System.DateTime> SoYTime { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
